### ISSUE TITLE
the code consultation accompanying the paper

### ISSUE THREAD

**Issue by YuQingGuoYu** [ibarrond/funshade#1]
I have recently read your paper: "Funshade: Functional Secret Sharing for Two-Party Secure Thresholded Distance Evaluation". The work is so interesting and I have studied it carefully.I try to validate your results of this work for a long time but no progress.I am wondering if you could kindly share the source program, dataset and the necessary information about it. I promise they will be used only for research purposed.

**Comment by ibarrond** [comment]
Hi @YuQingGuoYu , it took us a while, but the code is finally here! The dataset used (biometric templates) was generated using a proprietary feature extractor over the Labelled Faces in the Wild (LFW) dataset, which can be obtained online. Feel free to raise any other questions!
