### ISSUE TITLE
Grammatical errors in thesis sentences

### ISSUE THREAD

**Issue by YuQingGuoYu** [ibarrond/funshade#2]
2.1.4 On security guarantees.
In the second paragraph, "In contrast, FSS schemes FSS schemes rely on the security of the underlying PRG to be proven computationally secure against time bounded adversaries [11]."
Is there a syntax error in this sentence, two FSS schemes?

**Comment by ibarrond** [comment]
Indeed! thanks for pointing it out. A revised version will include this modification.
