### ISSUE TITLE
Building wheel for Funshade (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by ShokofehVS** [ibarrond/funshade#3]
**Description**
Installation with `pip install .` fails with an error.

**Code To Reproduce Error**
 `pip install .`

**Result (1) Before Installing libsodium Independently**
```
Defaulting to user installation because normal site-packages is not writeable
Processing /home/user/Documents/github/funshade
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.21 in /home/user/.local/lib/python3.8/site-packages (from Funshade==1.0.1) (1.24.2)
Building wheels for collected packages: Funshade
  Building wheel for Funshade (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for Funshade (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_ext
      cimporting numpy version '%s' 1.24.3
      building 'funshade' extension
      In file included from funshade/c/fss.c:1:
      funshade/c/fss.h:13:14: fatal error: sodium.h: No such file or directory
         13 |     #include "sodium.h"     // libsodium
            |              ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Funshade
Failed to build Funshade
ERROR: Could not build wheels for Funshade, which is required to install pyproject.toml-based projects
```
**Result (2) After Installing libsodium Independently**
```
Defaulting to user installation because normal site-packages is not writeable
Processing /home/user/Documents/github/funshade
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.21 in /home/user/.local/lib/python3.8/site-packages (from Funshade==1.0.1) (1.24.2)
Building wheels for collected packages: Funshade
  Building wheel for Funshade (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for Funshade (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_ext
      cimporting numpy version '%s' 1.24.3
      building 'funshade' extension
      funshade/py/funshade.c:1115:10: fatal error: numpy/arrayobject.h: No such file or directory
       1115 | #include "numpy/arrayobject.h"
            |          ^~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Funshade
Failed to build Funshade
ERROR: Could not build wheels for Funshade, which is required to install pyproject.toml-based projects
```

**Setup**
OS: Ubuntu 20.04
Python: 3.8.10
C compiler version: [GCC  9.4.0] on linux

**Note**
I tried to add `include_dirs=[numpy.get_include()]` into a `Setup.py` but it was not successful.

Thanks Alberto!

**Comment by ShokofehVS** [comment]
I've just understood that the problem `“fatal error: numpy/arrayobject.h: No such file or directory”` has two reasons. The one which makes the installation with failure was the fact that my compiler didn’t know where to find the `numpy/arrayobject.h` file.

Now Funshade is successfully installed and I could see the results for both scripts` test_funshade.py` and `test_fss.py`.  

Thanks Alberto for the changes!

**Comment by mialuyao** [comment]
> I've just understood that the problem `“fatal error: numpy/arrayobject.h: No such file or directory”` has two reasons. The one which makes the installation with failure was the fact that my compiler didn’t know where to find the `numpy/arrayobject.h` file.
> 
> Now Funshade is successfully installed and I could see the results for both scripts` test_funshade.py` and `test_fss.py`.
> 
> Thanks Alberto for the changes!

I get the same problem, how do you solve it? Thank you!

**Comment by ShokofehVS** [comment]
Hmhm, I should have documented the solution at that time as I can hardly remember how I fixed it :) 

However, [this](https://github.com/autonomousvision/unisurf/issues/3#issuecomment-1056896785) seemed to work for me at the end. You can alternatively follow the link on [Stackoverflow](https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory).

I hope this helps you find a solution. Anyways, Alberto can possibly give you some hints.

**Comment by mialuyao** [comment]
> Hmhm, I should have documented the solution at that time as I can hardly remember how I fixed it :)
> 
> However, [this](https://github.com/autonomousvision/unisurf/issues/3#issuecomment-1056896785) seemed to work for me at the end. You can alternatively follow the link on [Stackoverflow](https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory).
> 
> I hope this helps you find a solution. Anyways, Alberto can possibly give you some hints.

It works. 
Thank you for your prompt response.
