### ISSUE TITLE
Wrong result when I run test_fss.py

### ISSUE THREAD

**Issue by DMJYY** [ibarrond/funshade#5]
I found that when running funshade/py/test_fss.py file, the result did not pass the test in the code. How can I use DCF method correctly in funshade?

**Comment by ShokofehVS** [comment]
Hi @DMJYY, as far as I know, `test_fss.py` is not the part of paper for showing the functionality of Funshade as well as DCF. That being said, let's try `test_funshade.py`. There you can find how to design offline and online phases including `eval_sign`.

**Comment by DMJYY** [comment]
@ibarrond thank you! I tried test_funshade.py and get the right answer.
