### ISSUE TITLE
Funshade Security Parameters

### ISSUE THREAD

**Issue by ShokofehVS** [ibarrond/funshade#7]
**Description**
According to the Funshade's paper, if I understood it correctly, the experiment is performed over a range of factors including `n = 8, 16, 32, 64` (bits input) and $\lambda = 128$. 

**Question**
I would like to ask whether you could possibly help me know how to determine the involved security parameters prior to the execution. 

PS: I am having a lot fun :smiley: learning secret sharing with your project, Thanks a lot Alberto!

**Comment by ibarrond** [comment]
@ShokofehVS the security parameter is fixed and hardcoded to be $\lambda = 128$ bits.

**Comment by ShokofehVS** [comment]
All good, thanks!
